openShift: true

# Openshift overrides for collector
contrail-collector:
  openShift: true

opensearch:
  install: false

opensearch-dashboards:
  install: false

fluent-bit:
  install: false

influxdb2:
  securityContext:
    privileged: true

kube-prometheus-stack:
  install: false

emissary-ingress:
  install: false

fluentd:
  image:
    repository: hub.juniper.net/cn2/fluentd-kubernetes-daemonset
    tag: v1.13.3-debian-elasticsearch7-amd64-1.0
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcfluentd-main
    configMap:
      name: fluentd-main
      defaultMode: 0777
  - name: etcfluentd-config
    configMap:
      name: fluentd-config
      defaultMode: 0777
  - name: elasticsearch-templates
    configMap:
      name: elasticsearch-templates
      defaultMode: 0777
  - name: certs
    secret:
      secretName: es-secret

  volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcfluentd-main
    mountPath: /etc/fluent
  - name: etcfluentd-config
    mountPath: /etc/fluent/config.d/
  - name: elasticsearch-templates
    mountPath: /etc/elasticsearch-templates/
  - name: certs
    mountPath: /etc/fluent/cert/key
  fileConfigs:
    00_system.conf: |-
      <system>
        log_level debug
      </system>
    01_sources.conf: |-
      # logs directly sent to fluentd from sandesh components
      <source>
        @type forward
        bind 0.0.0.0
        port 24224
      </source>
    02_filters.conf: |-
      <filter>
        @type record_transformer
        <record>
          obj_tag ${tag}
        </record>
      </filter>
    03_dispatch.conf: |-
    04_outputs.conf: |-
      # send session logs to analytics collector
      <match contrail.SESSION.SessionEndpointObject>
        @type forward
        <server>
          name collector
          host collector
        </server>
        <secondary>
          @type stdout
        </secondary>
        heartbeat_interval 30
        ignore_network_errors_at_startup true
        keepalive true
      </match>

      # Send rest of the logs to elastic search
      <match **>
        @type elasticsearch
        host elasticsearch.openshift-logging.svc
        port 9200
        scheme https
        ssl_version TLSv1_2
        client_key '/etc/fluent/cert/key/tls.key'
        client_cert '/etc/fluent/cert/key/tls.crt'
        ca_file '/etc/fluent/cert/key/ca-bundle.crt'
        index_name app-write
        type_name _doc
        verify_es_version_at_startup false
        suppress_type_name true
      </match>
