tags:
  centralClusterComponents: true
  distributedClusterComponents: true

externalIP:
centralClusterIP: 0.0.0.0
openShift: false

contrail-collector:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  imagePullSecrets:
  - name: registrypullsecret

contrail-dashboard:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  imagePullSecrets:
  - name: registrypullsecret

contrail-introspect:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  imagePullSecrets:
  - name: registrypullsecret

contrail-multicluster-proxy:
  install:
  imagePullSecrets:
  - name: registrypullsecret

contrail-portal:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  imagePullSecrets:
  - name: registrypullsecret

contrail-telemetry-operator:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  # Comma separated metric-group names
  disabledMetricGroups:
  workers: 10
  imagePullSecrets:
  - name: registrypullsecret

contrail-grafana-customization:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:

opensearch:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install: 
  fullnameOverride: opensearch
  image:
    repository: hub.juniper.net/cn2/opensearch
    tag: "1.3.0"
  imagePullSecrets:
  - name: registrypullsecret
  persistence:
    image: hub.juniper.net/cn2/busybox
    storageClass: opensearch
  minimumMasterNodes: 1
  replicas: 1
  service:
    annotations:
      getambassador.io/config: |
        apiVersion: getambassador.io/v3alpha1
        kind:  Mapping
        name: opensearch
        hostname: "*"
        prefix: /opensearch/
        rewrite: /
        service: https://opensearch-cluster-master:9200
        timeout_ms: 15000
  volumeClaimTemplate:
    storageClassName: local
  securityContext:
    runAsUser: null
  podSecurityContext:
    fsGroup: null
    runAsUser: null
  rbac:
    create: true
  podSecurityPolicy:
    create: true
    spec:
      privileged: false
      allowPrivilegeEscalation: false
  extraInitContainers:
    ## Image that performs the sysctl operation to modify Kernel settings (needed sometimes to avoid boot errors)
    - name: sysctl
      image: hub.juniper.net/cn2/busybox
      imagePullPolicy: "IfNotPresent"
      command:
        - /bin/sh
        - -ec
        - |
          CURRENT=`sysctl -n vm.max_map_count`;
          DESIRED="262144";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w vm.max_map_count=262144;
          fi;
          CURRENT=`sysctl -n fs.file-max`;
          DESIRED="65536";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w fs.file-max=65536;
          fi;
      securityContext:
        runAsUser: 0
        privileged: true
  extraVolumes:
    - name: os-templates
      configMap:
        name: elasticsearch-templates
        defaultMode: 0777
  extraVolumeMounts:
    - name: os-templates
      mountPath: /etc/os-templates/
  lifecycle:
    postStart:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            #!/bin/bash
            TEMPLATE_NAME=contrail-kubernetes
            ES_URL=https://localhost:9200
            while [[ "$(curl --insecure -u 'admin:admin' -s -o /dev/null -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done
            curl -XPUT --insecure -u 'admin:admin' "$ES_URL/_template/$TEMPLATE_NAME" -H 'Content-Type: application/json' -d'@/etc/os-templates/contrail-kubernetes.json'

opensearch-dashboards:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  fullnameOverride: opensearch-dashboards
  opensearchHosts: "https://opensearch-cluster-master:9200"
  replicaCount: 1
  image:
    repository: hub.juniper.net/cn2/opensearch-dashboards
    tag: "1.3.0"
  imagePullSecrets:
  - name: registrypullsecret

  opensearchAccount:
    secret: ""
    keyPassphrase:
      enabled: false
      
  service:
    annotations:
      getambassador.io/config: |
        apiVersion: getambassador.io/v3alpha1
        kind:  Mapping
        name: opensearch-dashboards
        hostname: "*"
        prefix: /opensearch-dashboards/
        rewrite: /
        service: http://opensearch-dashboards:5601
        timeout_ms: 15000
  podSecurityContext:
    fsGroup: null
  securityContext:
    runAsUser: null
  config:
    opensearch_dashboards.yml: |
      server.basePath: /opensearch-dashboards
      server.host: "0"
      opensearch.hosts: ["https://opensearch-cluster-master:9200"]
      opensearch.ssl.verificationMode: none
      opensearch.username: "kibanaserver"
      opensearch.password: "kibanaserver"
      opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]

      opensearch_security.multitenancy.enabled: true
      opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
      opensearch_security.readonly_mode.roles: ["kibana_read_only"]
      # Use this setting if you are running opensearch-dashboards without https
      opensearch_security.cookie.secure: false

emissary-ingress:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  fullnameOverride: ambassador
  createDefaultListeners: true
  agent:
    enabled: false
  enableAES: false
  image:
    repository: hub.juniper.net/cn2/emissary
    tag: 2.2.2
  tlsName: tls-ambassador
  replicaCount: 1
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: contrail
  imagePullSecrets:
  - name: registrypullsecret

fluent-bit:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  logLevel: debug
  tolerations:
  - effect: NoSchedule
    operator: Exists
  fullnameOverride: fluentbit
  image:
    repository: hub.juniper.net/cn2/fluent-bit
    tag: "x86_64-1.8.14"
    pullPolicy: IfNotPresent
  imagePullSecrets:
  - name: registrypullsecret
  config:
    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*_contrail_*.log,/var/log/containers/*_kube-system_*.log
          Exclude_Path /var/log/containers/fluent*.log
          Parser crio
          Read_from_Head On
          Refresh_Interval 10
          Tag kube.*
          DB /var/log/fluentbit.db
          DB.locking On
      [INPUT]
          Name tail
          Path /var/log/containers/*_contrail-analytics_*.log,/var/log/containers/*_contrail-system_*.log
          Exclude_Path /var/log/containers/fluent*.log
          Parser cn2log
          Read_from_Head On
          Refresh_Interval 10
          Tag kube.*
          DB /var/log/fluentbit-cn2log.db
          DB.locking On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Labels Off
          Annotations Off
          Use_Kubelet Off
      [FILTER]
          Name record_modifier
          Match *
          Record cluster_name ${CLUSTERNAME}

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name forward
          Match kube.*
          Host fluentd
          Tag contrail.kubernetes

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    ## https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/logs/logs.go
    customParsers: |
      [PARSER]
          Name crio
          Format regex
          Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (F|P) (?<message>.*)$
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L%z
          Time_Keep On
      [PARSER]
          Name cn2log
          Format regex
          Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (F|P) (\S*)(\s)(?<level>\S*)(\s)(?<logger>\S*)(\s)(?<caller>\S*)(\s)(?<message>.*)$
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L%z
          Time_Keep On

fluentd:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  fullnameOverride: fluentd
  image:
    repository: hub.juniper.net/cn2/fluentd-kubernetes-daemonset
    tag: v1.14.5-debian-opensearch-amd64-1.0
  imagePullSecrets:
  - name: registrypullsecret
  kind: Deployment
  service:
    ports:
    - name: "forwarder"
      protocol: TCP
      containerPort: 24224

  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcfluentd-main
    configMap:
      name: fluentd-main
      defaultMode: 0777
  - name: etcfluentd-config
    configMap:
      name: fluentd-config
      defaultMode: 0777

  volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcfluentd-main
    mountPath: /etc/fluent
  - name: etcfluentd-config
    mountPath: /etc/fluent/config.d/

  fileConfigs:
    00_system.conf: |-
      <system>
        log_level debug
      </system>
    01_sources.conf: |-
      # logs directly sent to fluentd from sandesh components
      <source>
        @type forward
        bind 0.0.0.0
        port 24224
      </source>
    02_filters.conf: |-
    03_dispatch.conf: |-
    04_outputs.conf: |-
      # send session logs to analytics collector
      <match contrail.SESSION.SessionEndpointObject>
        @type forward
        <server>
          name collector
          host collector
        </server>
        <secondary>
          @type stdout
        </secondary>
        heartbeat_interval 30
        ignore_network_errors_at_startup true
        keepalive true
      </match>

      <match contrail.kubernetes>
        @type opensearch
        host opensearch-cluster-master
        port 9200
        scheme https
        ssl_verify false
        user admin
        password admin
        index_name contrail.kubernetes-%Y.%m.%d
        <buffer tag, time>
          timekey 10
          timekey_wait 60
          flush_thread_count 8
        </buffer>
      </match>

      # Send rest of the logs to elastic search
      <match **>
        @type opensearch
        host opensearch-cluster-master
        port 9200
        scheme https
        ssl_verify false
        user admin
        password admin
        logstash_format true
        time_key_format %Y-%m-%dT%H:%M:%S.%N%z
        logstash_prefix ${tag}
      </match>

influxdb2:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  adminUser:
    organization: contrail
  image:
    repository: hub.juniper.net/cn2/influxdb
    tag: "2.1.1-alpine"
  fullnameOverride: influxdb
  persistence:
    size: 30Gi
    storageClass: influxdb
    useExisting: true
  service:
    clusterIP: None
    port: 8086
  pdb:
    create: false
  serviceAccount:
    imagePullSecrets:
    - name: registrypullsecret

grafanaDatasourceInit:
  image:
    repository: hub.juniper.net/cn2/contrail-grafana-customizer
    tag: 22.2.0.93
  imagePullSecrets:
  - name: registrypullsecret

kube-prometheus-stack:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  fullnameOverride: prometheus
  global:
    imagePullSecrets:
    - name: registrypullsecret
  alertmanager:
    alertmanagerSpec:
      image:
        repository: hub.juniper.net/cn2/alertmanager
  prometheusOperator:
    admissionWebhooks:
      patch:
        image:
          repository: hub.juniper.net/cn2/kube-webhook-certgen
    image:
      repository: hub.juniper.net/cn2/prometheus-operator
    prometheusConfigReloader:
      image:
        repository: hub.juniper.net/cn2/prometheus-config-reloader
  prometheus:
    prometheusSpec:
      image:
        repository: hub.juniper.net/cn2/prometheus
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: prometheus
            resources:
              requests:
                storage: 30Gi

  grafana:
    downloadDashboardsImage:
      repository: hub.juniper.net/cn2/curl
    fullnameOverride: grafana
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
        serve_from_sub_path: "true"
    image:
      repository: hub.juniper.net/cn2/grafana
      pullSecrets:
      - registrypullsecret
    initChownData:
      image:
        repository: hub.juniper.net/cn2/busybox
    service:
      annotations:
        getambassador.io/config: |
          apiVersion: getambassador.io/v3alpha1
          kind:  Mapping
          name: grafana
          hostname: "*"
          prefix: /grafana/
          rewrite: /
          service: grafana
          timeout_ms: 15000
    sidecar:
      image:
        repository: hub.juniper.net/cn2/k8s-sidecar
        tag: 1.16.0
  kube-state-metrics:
    fullnameOverride: state-metrics
    image:
      repository: hub.juniper.net/cn2/kube-state-metrics
    imagePullSecrets:
    - name: registrypullsecret
  prometheus-node-exporter:
    fullnameOverride: node-exporter
    image:
      repository: hub.juniper.net/cn2/node-exporter
    serviceAccount:
      imagePullSecrets:
      - name: registrypullsecret

thanos:
    image:
      repository: hub.juniper.net/cn2/thanos
      tag: v0.24.0
    store:
      enabled: false
    compact:
      enabled: false
    bucket:
      enabled: false
    rule:
      enabled: false
    sidecar:
      enabled: false
    queryFrontend:
      enabled: false
    query:
      enabled: false
      replicaLabels:
        - prometheus_replica
      stores:
      - dnssrv+_grpc._tcp.prometheus-operated

kruise:
  installation:
    namespace: kruise-system
  featureGates: "PodWebhook=false"
  manager:
    image:
      repository: hub.juniper.net/cn2/kruise-manager
  imagePullSecrets:
  - name: registrypullsecret

storage:
  # Default behavior for installallation is based on the chart's tags specified in
  # Chart.yaml. A value for install parameter below should only be specified when
  # overriding the default behavior
  install:
  storageclass: local
  customizer:
    image:
      repository: hub.juniper.net/cn2/contrail-storage-customizer
      tag: 22.2.0.93
    imagePullSecrets:
    - name: registrypullsecret

curl:
  image:
    repository: hub.juniper.net/cn2/curl
    tag: latest
  imagePullSecrets:
  - name: registrypullsecret

helmutil:
  image:
    repository: hub.juniper.net/cn2/helmutil
    tag: 0.0.1-g785d013b6c
  imagePullSecrets:
  - name: registrypullsecret
