apiVersion: v1
kind: Service
metadata:
  name: multicluster-proxy
  namespace: {{ .Release.Namespace }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: getambassador.io/v3alpha1
      kind:  Mapping
      name:  cn2_auth
      hostname: "*"
      prefix: /cn2/auth/
      rewrite: /auth/
      service: https://multicluster-proxy.{{ .Release.Namespace }}:9090
      timeout_ms: 15000
      ---
      apiVersion: getambassador.io/v3alpha1
      kind:  Mapping
      name:  cn2_clusters
      hostname: "*"
      prefix: /cn2/clusters
      rewrite: /clusters
      service: https://multicluster-proxy.{{ .Release.Namespace }}:9090
      timeout_ms: 15000
      ---
      apiVersion: getambassador.io/v3alpha1
      kind:  Mapping
      name:  cn2_rbac
      hostname: "*"
      prefix: /cn2/rbac
      rewrite: /rbac
      service: https://multicluster-proxy.{{ .Release.Namespace }}:9090
      timeout_ms: 15000
      ---
      apiVersion: getambassador.io/v3alpha1
      kind:  Mapping
      name:  cn2_kubeapi
      hostname: "*"
      prefix: /kubeapi/
      rewrite: /kubeapi/
      service: https://multicluster-proxy.{{ .Release.Namespace }}:9090
      timeout_ms: 30000
      ---
      apiVersion: getambassador.io/v3alpha1
      kind:  Mapping
      name:  prometheus_mapping
      hostname: "*"
      prefix: /prometheus/
      rewrite: /prometheus/
      service: https://multicluster-proxy.{{ .Release.Namespace }}:9090
      timeout_ms: 30000
spec:
  type: ClusterIP
  selector:
    app: multicluster-proxy
  ports:
    - name: rest
      protocol: TCP
      port: 9090
      targetPort: 9090
