apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-influxdb-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  influxdb-grafana-datasource.yaml: |-
    # config file version
    apiVersion: 1
    datasources:
      - name: InfluxDB
        editable: true
        type: influxdb
        access: proxy
        url: "http://influxdb.{{ .Release.Namespace }}:8086"
        basicAuth: false
        withCredentials: false
        jsonData:
          defaultBucket: cn2_ds
          httpHeaderName1: Auhorization
          httpMode: POST
          maxSeries: 100
          organization: contrail
          timeInterval: 1m
          version: Flux
        secureJsonFields:
          httpHeaderValue1: true
          token: false
        secureJsonData:
          token: ""
