apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: {{ .Release.Namespace }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: getambassador.io/v3alpha1
      kind:  Mapping
      name:  portal_api_gateway
      hostname: "*"
      prefix: /
      service: portal.{{ .Release.Namespace }}:8082
      retry_policy:
        retry_on: "5xx"
        num_retries: 3
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 3000
      protocol: TCP
  selector:
    app: portal
