
{{- $ca := genCA "telemetry-operator-webhook-service" 730 -}}
{{- $cert := genSignedCert (printf "telemetry-operator-webhook-service.%s.svc" .Release.Namespace) nil (list (printf "telemetry-operator-webhook-service.%s.svc" .Release.Namespace)) 365 $ca -}}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.webhookSecretName }}
stringData:
  tls.crt: |-
{{ indent 4 $cert.Cert }}
  tls.key: |-
{{ indent 4 $cert.Key }}
  ca.crt: |-
{{ indent 4 $ca.Cert }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: telemetry-operator-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: telemetry-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-telemetry-juniper-net-v1alpha1-metricgroup
  failurePolicy: Fail
  name: vmetricgroup.kb.io
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  rules:
  - apiGroups:
    - telemetry.juniper.net
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - metricgroups
