apiVersion: v1
kind: Service
metadata:
  name: introspect
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: introspect
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: {{ .Values.api.version }}.{{ .Values.api.group }}
spec:
  service:
    name: introspect
    namespace: {{ .Release.Namespace }}
  group: {{ .Values.api.group }}
  version: {{ .Values.api.version }}
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
