apiVersion: v1
kind: ConfigMap
metadata:
  name: collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: collector
data:
  config.yaml: |-
    log:
      caller: true
      level:
        default: debug
    http_port: 9090
    tls_config:
      server_name: localhost
      key_file: /etc/config/server.key
      cert_file: /etc/config/server.crt
      ca_file: /etc/config/ca.crt
    Source:
      - Encoding: json
        ListenOn: 5170
      - Encoding: msgpack
        ListenOn: 24224
    Databases:
      InfluxDB:
        URL: "http://influxdb.{{ .Release.Namespace }}:8086"
        Organization: {{ .Values.database.influx.organization }}
        Bucket: {{ .Values.database.influx.bucket }}
        Token: ""
        DownsampleBucket: "cn2_ds"
        DownsampleDuration: 300
        DownsampleRetention: 2592000
        DownsampleQueryFile: /etc/config/influxdb_downsample_query.flux
