{{- if .Values.openShift -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: collector
  namespace: contrail-analytics
spec:
  port:
    targetPort: 9090
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: collector
    weight: 100
  wildcardPolicy: None
{{ end }}
