---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: collector
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collector
rules:
- apiGroups:
  - "core.contrail.juniper.net"
  resources:
  - tags
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: collector
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector
subjects:
- kind: ServiceAccount
  name: collector
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collector
