apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: {{ .Release.Namespace }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: getambassador.io/v3alpha1
      kind:  Mapping
      name:  collector_rest
      hostname: "*"
      prefix: /collector/
      rewrite: /collector/
      service: https://collector.{{ .Release.Namespace }}:9090
      timeout_ms: 15000
spec:
  type: ClusterIP
  selector:
    app: collector
  ports:
    - name: rest
      protocol: TCP
      port: 9090
    - name: json
      protocol: TCP
      port: 5170
    - name: msgpack
      protocol: TCP
      port: 24224
