{{- if ne (include "installFluentd" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-central-forwarding
data:
  custom_parsers.conf: |
    {{- index .Values "fluent-bit" "config" "customParsers" | nindent 4 }}
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level {{ index .Values "fluent-bit" "logLevel" }}
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
    {{ index .Values "fluent-bit" "config" "inputs" | nindent 4 -}}
    {{ index .Values "fluent-bit" "config" "filters" | nindent 4 }}
    [OUTPUT]
        Name forward
        Match kube.*
        Host {{ .Values.centralClusterIP }}
        Tag contrail.kubernetes
{{ end }}
