{{- if eq (include "installFluentd" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: contrail
  name: fluentd-loadbalancer
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: forwarder
    port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
  type: LoadBalancer
{{ end }}
