{{- if (lookup "v1" "Secret" "contrail-analytics" "registrypullsecret") }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kruise-cp-secret-{{ .Chart.Version }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: analyticsinstall
      containers:
      - name: init
        image: {{ .Values.helmutil.image.repository }}:{{ .Values.helmutil.image.tag }}
        args:
          - copysecret
        env:
          - name: SRC_NAMESPACE
            value: contrail-analytics
          - name: SRC_SECRET
            value: registrypullsecret
          - name: SRC_KEYS
            value: .dockerconfigjson
          - name: DST_NAMESPACE
            value: kruise-system
          - name: DST_SECRET
            value: registrypullsecret
{{- if .Values.helmutil.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.helmutil.imagePullSecrets | indent 8 }}
      {{- end }}
{{ end }}
