{{- if .Values.openShift -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:privileged
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: analyticsinstall
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: influxdb
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: introspect
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: fluentd
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: fluentbit
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kruise-manager-broadcastjob-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - broadcastjobs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kruise-manager-broadcastjob-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kruise-manager-broadcastjob-role
subjects:
  - kind: ServiceAccount
    name: kruise-manager
    namespace: {{ .Values.kruise.installation.namespace }}
{{ end }}
