{{- if .Values.openShift -}}
{{- if eq (include "installInfluxdb2" .) "true" -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ocp-cp-secret-{{ .Chart.Version }}
spec:
  backoffLimit: 1000000
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: analyticsinstall
      containers:
      - name: init
        image: {{ .Values.helmutil.image.repository }}:{{ .Values.helmutil.image.tag }}
        args:
          - copysecret
        env:
          - name: SRC_NAMESPACE
            value: openshift-logging
          - name: SRC_SECRET
            value: collector
          - name: SRC_KEYS
            value: tls.crt,tls.key,ca-bundle.crt
          - name: DST_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: DST_SECRET
            value: es-secret
{{- if .Values.helmutil.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.helmutil.imagePullSecrets | indent 8 }}
      {{- end }}
{{ end }}
{{ end }}
