---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analyticsinstall
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
{{ toYaml .Values.influxdb2.serviceAccount.imagePullSecrets | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: analyticsinstall
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: analyticsinstall
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analyticsinstall
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: analyticsinstall
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: analyticsinstall
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: analyticsinstall
subjects:
- kind: ServiceAccount
  name: analyticsinstall
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: analyticsinstall
