{{- if eq (include "installAmbassador" .) "true" -}}
{{- $cert := genSelfSignedCert "ambassador" nil (list (printf "ambassador.%s" .Release.Namespace)) 730 -}}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ (index .Values "emissary-ingress" "tlsName") }}
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-host
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  tlsSecret:
    name: {{ (index .Values "emissary-ingress" "tlsName") }}
  selector:
    matchLabels:
      hostname: wildcard-host
{{ end }}
